# Generated by Django 4.0.5 on 2022-07-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='actors', through='mtoms.ActorMovie', to='mtoms.movie'),
        ),
    ]
