# Generated by Django 4.0.5 on 2022-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0002_alter_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.AddField(
            model_name='actor',
            name='movie_list',
            field=models.CharField(default='', max_length=100),
        ),
    ]
