# Generated by Django 4.0.5 on 2022-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0003_remove_actor_movie_actor_movie_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth',
            field=models.DateField(),
        ),
    ]
