# Generated by Django 4.0.5 on 2022-07-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0004_alter_actor_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie_list',
        ),
    ]
