# Generated by Django 4.0.5 on 2022-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0005_remove_actor_movie_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(to='mtoms.movie'),
        ),
        migrations.DeleteModel(
            name='ActorMovie',
        ),
    ]
