# Generated by Django 4.0.6 on 2022-08-02 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0007_alter_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.CreateModel(
            name='ActorMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actormovies', to='mtoms.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actormovies', to='mtoms.movie')),
            ],
            options={
                'db_table': 'actormovies',
            },
        ),
    ]
