# Generated by Django 4.0.6 on 2022-08-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0008_remove_actor_movie_actormovies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorMovies',
            new_name='ActorMovie',
        ),
    ]
