# Generated by Django 4.0.6 on 2022-08-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0009_rename_actormovies_actormovie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorMovie',
            new_name='ActorMovies',
        ),
    ]
