# Generated by Django 4.0.6 on 2022-08-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtoms', '0010_rename_actormovie_actormovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
    ]
